#ifndef ROBOTMAP_H
#define ROBOTMAP_H


const struct {
	UINT8 DIGITAL_MODULE_PORT_CHANNEL = 2,
	      SOLENOID_MODULE_PORT_CHANNEL = 3;
	
	UNIT32 SHOOTER_MOTOR_0_CHANNEL = 0,
	       SHOOTER_MOTOR_1_CHANNEL = 0,
	       SHOOTER_ENCODER_A_CHANNEL = 0,
	       SHOOTER_ENCODER_B_CHANNEL = 0,
	       SHOOTER_PUSHER_SPIKE_CHANNEL = 0,
	       SHOOTER_LOADER_SOLENOID_CHANNEL_EXTEND = 0,
	       SHOOTER_LOADER_SOLENOID_CHANNEL_RETRACT = 0;
} ROBOT_MAP;
#endif // ROBOTMAP_H
